# Generated by Django 3.2.5 on 2021-07-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210719_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joined',
        ),
    ]
